/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Blender3D (https://sketchfab.com/Blender3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basic-bowl-d6af7797763d41d3a89af10d726e2256
Title: Basic Bowl
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
    const { nodes } = useGLTF('/models/basic_bowl.glb')
    const instances = useMemo(
        () => ({
            Object: nodes.Object_2,
        }),
        [nodes]
    )
    return (
        <Merged meshes={instances} {...props}>
            {(instances) => <context.Provider value={instances} children={children} />}
        </Merged>
    )
}

export function Model(props) {
    const instances = useContext(context)
    return (
        <group {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    rotation={[-Math.PI / 2, 0, 0]}
                    userData={{ name: 'Sketchfab_model' }}>
                    <group
                        name="Bowlobjcleanermaterialmergergles"
                        userData={{ name: 'Bowl.obj.cleaner.materialmerger.gles' }}>
                        <instances.Object name="Object_2" userData={{ name: 'Object_2' }} />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/basic_bowl.glb')