/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ry1nArt (https://sketchfab.com/Ry1nArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paperclip-98b3ae9f553642808547abc9149a61d0
Title: Paperclip
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const PAPERCLIP_MODEL_URL = '/models/paperclip.v1.glb'

export function Model(props) {
    const { nodes, materials } = useGLTF(PAPERCLIP_MODEL_URL)
    return (
        <group {...props} dispose={null}>
            <group rotation={[0.83, -0.292, 0.283]} scale={0.013}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <mesh
                        geometry={nodes.Paperclip_Material_0.geometry}
                        material={materials.Material}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={10000}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(PAPERCLIP_MODEL_URL)
