/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Akio INAGAKI (https://sketchfab.com/AkioINAGAKI)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tool-tajima-cutter-37ce4a5cd57849559c29a479a35c6e51
Title: Tool Tajima Cutter
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
    const { nodes, materials } = useGLTF('/models/tool_tajima_cutter.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-0.686, -0.053, 0.065]}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.blade_low_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-21.943, 1.252, -2.614]}
                        scale={[1, 0.712, 1.21]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.slider_low_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[18.598, 19.686, -2.23]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.267, 1.328, 0.472]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.clip_low_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[77.193, 1.529, -1.689]}
                        scale={[1, 0.327, 1.148]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.inside_Metal_low_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[0, 0, -0.018]}
                        scale={[1, 1, 0.989]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.body_low_lambert1_0.geometry}
                        material={materials.lambert1}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/tool_tajima_cutter.glb')
