/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pencil-e67db84c8d2442519353afbae5220de0
Title: Pencil
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const PENCIL_MODEL_URL = '/models/pencil.v1.glb'

export function Model(props) {
    const { nodes, materials } = useGLTF(PENCIL_MODEL_URL)
    return (
        <group {...props} dispose={null}>
            <group position={[16.901, -6.654, -13.896]} rotation={[-1.973, 0.445, 1.71]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[0, 82.073, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[5.687, 5.687, 13.907]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_black_0.geometry}
                            material={materials.black}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_red_0.geometry}
                            material={materials.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder_chol_0.geometry}
                            material={materials.chol}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(PENCIL_MODEL_URL)
